Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: mycooluser
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
  MyInlinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyInlinePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "ec2:*"
            Resource: "*"
      Users:
        - !Ref MyUser