#!/bin/bash

#check if the bucket name is provided
if [ -z "$1" ]; then
  echo "There needs to be a bucket name provided"
  echo "Usage: $0 <bucket-name>"
  exit 1
fi

aws s3api \
create-bucket \
--bucket "$1" --region ap-south-1 \
--create-bucket-configuration LocationConstraint=ap-south-1 \
--query 'Location' \
--output text

if [ $? -ne 0 ]; then
  echo "Failed to create bucket $1"
  exit 1
fi
echo "Bucket $1 created successfully"