#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <vpc-id>"
    exit 1
fi
VPC_ID=$1
echo "Deleting VPC with ID: $VPC_ID"

#detach and delete internet gateway
aws ec2 detach-internet-gateway \
    --internet-gateway-id $(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$VPC_ID" --query 'InternetGateways[0].InternetGatewayId' --output text) \
    --vpc-id "$VPC_ID" \
    --region ap-south-1
aws ec2 delete-internet-gateway \
    --internet-gateway-id $(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$VPC_ID" --query 'InternetGateways[0].InternetGatewayId' --output text) \
    --region ap-south-1

#delete route table
aws ec2 delete-route-table \
    --route-table-id $(aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$VPC_ID" --query 'RouteTables[0].RouteTableId' --output text) \
    --region ap-south-1
#delete subnets
aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query 'Subnets[*].SubnetId' --output text | xargs -I {} aws ec2 delete-subnet --subnet-id {} --region ap-south-1
#delete vpc
aws ec2 delete-vpc \
    --vpc-id "$VPC_ID" \
    --region ap-south-1

echo "VPC with ID $VPC_ID and its associated resources have been deleted."